resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: a2607ec4986602d04e00667d477dfb590bee8df9
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
