resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: a1b09aaedce80690c08c2f9507fa84dd4866f259
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
