resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: b40f2e87458e222fd4bf4eef79916f3b52f55ee7
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
