resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: 595716530bf3fb82ae16c041b962e86c7b468f1d
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
