resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: be505a98ac066ab28963368e13a079e81f3e6cad
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
