resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: c5747133e237099c6a5bdd4f0151326b555b0d45
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
