resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: eb9a317e27dae8e5896fbd35e44dc7204c747146
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
