resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: 99a90bb7fdc2b33b65dfab82d248ca61663470f6
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
