resources:
- ../../base
images:
- name: sample-app
  newName: registry.local:5000/sample-app
  newTag: df97be95d8488effe8ef4f4a23f42b6b38bc167a
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
